src/main/java/com/tourgether/tourgether/language/entity/Language.java, src/main/java/com/tourgether/tourgether/member/entity/Member.java, src/main/java/com/tourgether/tourgether/member/enums/Provider.java, src/main/java/com/tourgether/tourgether/member/enums/Status.java
- #10 
- member entity
- languae entity
=> feat: member, language entity

src/main/java/com/tourgether/tourgether/common/dto/ApiResponse.java, src/main/java/com/tourgether/tourgether/common/exception/GlobalExceptionHandler.java
- #31 
- 공통응답 DTO
- GlobalExceptionHandler
-
=> feat: 공통응답 DTO, GlobalExceptionHandler

src/main/java/com/tourgether/tourgether/member/controller/MemberController.java, src/main/java/com/tourgether/tourgether/member/dto/request/NicknameUpdateRequest.java, src/main/java/com/tourgether/tourgether/member/dto/response/NicknameUpdateResponse.java, src/main/java/com/tourgether/tourgether/member/entity/Member.java, src/main/java/com/tourgether/tourgether/member/repository/MemberRepository.java, src/main/java/com/tourgether/tourgether/member/service/MemberService.java, src/main/java/com/tourgether/tourgether/member/service/impl/MemberServiceImpl.java
- #22 
- 회원의 닉네임 수정 기능
- MemberService에서 회원 조회 공통 코드 MemberRepository에 메서드로 추가
=> feat: nickname update

src/main/java/com/tourgether/tourgether/member/controller/MemberController.java, src/main/java/com/tourgether/tourgether/member/dto/response/MemberInfoResponse.java, src/main/java/com/tourgether/tourgether/member/service/MemberService.java, src/main/java/com/tourgether/tourgether/member/service/impl/MemberServiceImpl.java
=> feat: 내 정보 조회(마이페이지)

build.gradle, src/main/java/com/tourgether/tourgether/attraction/entity/Attraction.java, src/main/java/com/tourgether/tourgether/attraction/entity/AttractionTranslation.java, src/main/java/com/tourgether/tourgether/attraction/entity/Quiz.java, src/main/java/com/tourgether/tourgether/common/config/SecurityConfig.java, src/main/java/com/tourgether/tourgether/common/config/SwaggerConfig.java, src/main/java/com/tourgether/tourgether/common/exception/BadRequestException.java, src/main/java/com/tourgether/tourgether/common/exception/GlobalExceptionHandler.java, src/main/java/com/tourgether/tourgether/common/exception/ResourceNotFoundException.java
- 
- 공통예외처리 추가
- 퀴즈엔티티 추가, 관광지 엔티티에 썸네일이미지 필드 추가
-
=> feat: 공통작업

src/main/java/com/tourgether/tourgether/attraction/controller/AttractionController.java, src/main/java/com/tourgether/tourgether/attraction/controller/AttractionControllerDocs.java, src/main/java/com/tourgether/tourgether/attraction/repository/AttractionTranslationRepository.java, src/main/java/com/tourgether/tourgether/attraction/service/AttractionService.java, src/main/java/com/tourgether/tourgether/attraction/service/impl/AttractionServiceImpl.java, src/test/java/com/tourgether/tourgether/attraction/controller/AttractionControllerTest.java, src/test/java/com/tourgether/tourgether/attraction/service/AttractionServiceTest.java
- #25 
- 인기 관광지 조회 기능
- 여행지 상세 조회 변경(translationId로 조회)
-
=> feat: 인기 관광지 조회 기능 추가

src/main/java/com/tourgether/tourgether/route/client/ODsayClient.java, src/main/java/com/tourgether/tourgether/route/controller/RouteController.java, src/main/java/com/tourgether/tourgether/route/controller/RouteControllerDocs.java, src/main/java/com/tourgether/tourgether/route/dto/response/RouteLaneResponse.java, src/main/java/com/tourgether/tourgether/route/dto/response/RouteSearchResponse.java, src/main/java/com/tourgether/tourgether/route/service/RouteService.java, src/main/java/com/tourgether/tourgether/route/service/impl/RouteServiceImpl.java, src/main/resources/application.yml
- #29 
- odsay 대중교통 길안내 api
- odsay 노선 그래픽 데이터 api
-
=> feat: odsay api 구현

.idea/misc.xml, src/main/java/com/tourgether/tourgether/attraction/exception/AttractionNotFoundException.java, src/main/java/com/tourgether/tourgether/attraction/repository/AttractionTranslationRepository.java, src/main/java/com/tourgether/tourgether/visit/controller/VisitController.java, src/main/java/com/tourgether/tourgether/visit/dto/response/VisitCreateResponse.java, src/main/java/com/tourgether/tourgether/visit/dto/response/VisitResponse.java, src/main/java/com/tourgether/tourgether/visit/repository/VisitRepository.java, src/main/java/com/tourgether/tourgether/visit/service/VisitService.java, src/main/java/com/tourgether/tourgether/visit/service/impl/VisitServiceImpl.java
=> feat: 방문내역조회

src/main/java/com/tourgether/tourgether/attraction/controller/AttractionController.java, src/main/java/com/tourgether/tourgether/attraction/controller/AttractionControllerDocs.java, src/main/java/com/tourgether/tourgether/attraction/dto/AttractionMapSummaryResponse.java, src/main/java/com/tourgether/tourgether/attraction/repository/AttractionTranslationRepository.java, src/main/java/com/tourgether/tourgether/attraction/service/AttractionService.java, src/main/java/com/tourgether/tourgether/attraction/service/impl/AttractionServiceImpl.java
=> feat: 지도 내 관광지 검색 기능 구현

src/main/java/com/tourgether/tourgether/attraction/controller/AttractionController.java, src/main/java/com/tourgether/tourgether/attraction/controller/AttractionControllerDocs.java, src/main/java/com/tourgether/tourgether/attraction/entity/Attraction.java, src/main/java/com/tourgether/tourgether/attraction/enums/Area.java, src/main/java/com/tourgether/tourgether/attraction/repository/AttractionTranslationRepository.java, src/main/java/com/tourgether/tourgether/attraction/service/AttractionService.java, src/main/java/com/tourgether/tourgether/attraction/service/impl/AttractionServiceImpl.java, src/main/java/com/tourgether/tourgether/common/config/SecurityConfig.java, src/test/java/com/tourgether/tourgether/attraction/controller/AttractionControllerTest.java, src/test/java/com/tourgether/tourgether/attraction/repository/AttractionTranslationRepositoryTest.java, src/test/java/com/tourgether/tourgether/attraction/service/AttractionServiceTest.java
- 
- 관광지 엔티티에 권역(area)필드 enum 타입으로 추가
- 유저가 많이 방문한 관광지 목록 조회 권역 타입 추가하여 조회하도록 변경
-
=> refactor: Top 방문지 목록 조회 수정

src/main/java/com/tourgether/tourgether/route/dto/response/RouteSearchResponse.java
=> refactor: odsay 응답 dto 변경

src/main/java/com/tourgether/tourgether/attraction/controller/AttractionLikeController.java, src/main/java/com/tourgether/tourgether/attraction/dto/AttractionLikeResponse.java, src/main/java/com/tourgether/tourgether/attraction/entity/Attraction.java, src/main/java/com/tourgether/tourgether/attraction/entity/AttractionLike.java, src/main/java/com/tourgether/tourgether/attraction/entity/AttractionLikeId.java, src/main/java/com/tourgether/tourgether/attraction/repository/AttractionLikeRepository.java, src/main/java/com/tourgether/tourgether/attraction/service/AttractionLikeService.java, src/main/java/com/tourgether/tourgether/attraction/service/impl/AttractionLikeServiceImpl.java, src/main/java/com/tourgether/tourgether/common/config/SecurityConfig.java, src/main/java/com/tourgether/tourgether/member/entity/Member.java, src/main/java/com/tourgether/tourgether/visit/controller/VisitController.java
=> feat: 좋아요 기능

src/main/java/com/tourgether/tourgether/language/controller/LanguageController.java, src/main/java/com/tourgether/tourgether/language/dto/LanguageResponse.java, src/main/java/com/tourgether/tourgether/language/service/LanguageService.java, src/main/java/com/tourgether/tourgether/language/service/impl/LanguageServiceImpl.java, src/main/java/com/tourgether/tourgether/member/controller/MemberController.java, src/main/java/com/tourgether/tourgether/member/dto/request/LanguageUpdateRequest.java, src/main/java/com/tourgether/tourgether/member/dto/response/MemberInfoResponse.java, src/main/java/com/tourgether/tourgether/member/service/MemberService.java, src/main/java/com/tourgether/tourgether/member/service/impl/MemberServiceImpl.java
- #18 
- 언어 조회 추가
- 언어 조회를 위한 dto 및 메서드 수정
-
=> refactor: language

.github/workflows/prod-cd-actions.yml
- 
- cd 스크립트 도커컴포즈 prod파일 실행으로 수정
-
=> fix: 도커컴포즈 prod파일로 실행 명시

.github/workflows/prod-cd-actions.yml, src/main/resources/application-prod.yml
=> fix: validate문제와 secrets오기입 수정

.github/workflows/prod-cd-actions.yml, src/main/resources/application-prod.yml
=> fix/infra 

.github/workflows/prod-cd-actions.yml, src/main/resources/application-prod.yml
* fix: validate문제와 secrets오기입 수정
* fix: 도커 컨테이너 내부에서 스프링서버 에러로 인한 임시 수정
- 
- 
-
=> fix/infra  재배포

.github/workflows/prod-cd-actions.yml
=> fix: cd env 복사 스크립트 에러로인한 수정

.idea/dataSources.xml, src/main/java/com/tourgether/tourgether/member/controller/MemberController.java, src/main/java/com/tourgether/tourgether/visit/controller/VisitController.java
- 
- attraction controller, visit controller 하드코딩 수정
-
=> fix: 하드코딩 수정

.github/workflows/prod-cd-actions.yml
=> refactor: 이미지 변경 시 컨테이너 다시만들고 시작하도록 수정

.github/workflows/prod-cd-actions.yml
=> 5/3 1차 재배포

src/main/java/com/tourgether/tourgether/common/config/SecurityConfig.java
=> fix: corsConfigSource

src/main/java/com/tourgether/tourgether/common/config/SecurityConfig.java
=> fix: cors 에러

src/main/java/com/tourgether/tourgether/attraction/entity/AttractionTranslation.java
=> chore: summary 컬럼을 TEXT 타입으로 수정

src/main/java/com/tourgether/tourgether/attraction/entity/AttractionTranslation.java
=> chore: summary 컬럼을 TEXT 타입으로 수정 (#108)
